### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by tcgumus** [mfatihaktas/mfatihaktas.github.io#1]
Look like shit bro

**Comment by mfatihaktas** [comment]
:D biliyom cok cirkin, ama zaman ayirip duzeltemedim.
Geliyorum insallah, Istanbul ucagina biniyorum simdi.
Bulusunce beraber duzeltelim :)

**Comment by tcgumus** [comment]
Ok lets fix it together! We should use netlify and tailwindscss.
check this out
https://dev.to/tcgumus/install-gatsby-add-tailwind-css-to-it-and-deploy-it-to-netlify-a-simple-website-example-3cdh

**Comment by mfatihaktas** [comment]
Cool! 👍
